### ISSUE TITLE
Do not support multiple _acme-challenge records

### ISSUE THREAD

**Issue by KocourKuba** [ethauvin/namesilo-letsencrypt#1]
If you have more than one record script failed.

**Comment by ethauvin** [comment]
@KocourKuba 

I only use it with multiple records, it works for me.

What I have noticed lately is that Namesilo is taking more than 15 minutes to update the DNS records. It is intermittent but when it happens Certbot is not able to complete the challenge, which results in the certificate not being issued or renewed.

I've just released a [new version](https://github.com/ethauvin/namesilo-letsencrypt/releases/tag/0.9.1) that increases the wait time to 20 minutes. You can actually configure the wait time to anything you want, but 20 minutes seems to have worked for me in the last few weeks.

Let me know if that works for you too.
