### ISSUE TITLE
Files in latest namesilo-letsencrypt-0.9.2.tar.gz are in DOS format. certbot run fails

### ISSUE THREAD

**Issue by vinayakrk** [ethauvin/namesilo-letsencrypt#3]
Hi there -
While trying to figure out why I was getting the following errors when running the certbot command, I realized the files contained in the 0.9.2 tar.gz are in DOS format. 
<pre>
root@i7:~/namesilo-letsencrypt-0.9.2# ./doit.sh 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for domain.masked
dns-01 challenge for domain.masked
Running manual-auth-hook command: /root/namesilo-letsencrypt-0.9.2/authenticator.py
manual-auth-hook command "/root/namesilo-letsencrypt-0.9.2/authenticator.py" returned error code 127
Error output from manual-auth-hook command authenticator.py:
/bin/sh: 1: /root/namesilo-letsencrypt-0.9.2/authenticator.py: not found

Running manual-auth-hook command: /root/namesilo-letsencrypt-0.9.2/authenticator.py
manual-auth-hook command "/root/namesilo-letsencrypt-0.9.2/authenticator.py" returned error code 127
Error output from manual-auth-hook command authenticator.py:
/bin/sh: 1: /root/namesilo-letsencrypt-0.9.2/authenticator.py: not found

Waiting for verification...
Challenge failed for domain domain.masked
Challenge failed for domain domain.masked
dns-01 challenge for domain.masked
dns-01 challenge for domain.masked
Cleaning up challenges
Running manual-cleanup-hook command: /root/namesilo-letsencrypt-0.9.2/cleanup.py
manual-cleanup-hook command "/root/namesilo-letsencrypt-0.9.2/cleanup.py" returned error code 127
Error output from manual-cleanup-hook command cleanup.py:
/bin/sh: 1: /root/namesilo-letsencrypt-0.9.2/cleanup.py: not found

Running manual-cleanup-hook command: /root/namesilo-letsencrypt-0.9.2/cleanup.py
manual-cleanup-hook command "/root/namesilo-letsencrypt-0.9.2/cleanup.py" returned error code 127
Error output from manual-cleanup-hook command cleanup.py:
/bin/sh: 1: /root/namesilo-letsencrypt-0.9.2/cleanup.py: not found

Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: domain.masked
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.domain.masked - check that a DNS record exists for
   this domain

   Domain: domain.masked
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.domain.masked - check that a DNS record exists for
   this domain
root@i7:~/namesilo-letsencrypt-0.9.2# 
root@i7:~/namesilo-letsencrypt-0.9.2# cat doit.sh 
certbot certonly --staging --manual --email domain.masked@gmail.com \
  --agree-tos --manual-public-ip-logging-ok \
  --preferred-challenges=dns \
  --manual-auth-hook /root/namesilo-letsencrypt-0.9.2/authenticator.py \
  --manual-cleanup-hook /root/namesilo-letsencrypt-0.9.2/cleanup.py \
  -d *.domain.masked -d domain.masked
root@i7:~/namesilo-letsencrypt-0.9.2# 

root@i7:~/new/namesilo-letsencrypt-0.9.2# cksum *
1979043218 3311 authenticator.py
2915655169 1050 CHANGELOG.md
82618259 3112 cleanup.py
1942701120 151 config.py
3311993660 1536 LICENSE.txt
2424547664 1771 README.md
root@i7:~/new/namesilo-letsencrypt-0.9.2# dos2unix *
dos2unix: converting file authenticator.py to Unix format...
dos2unix: converting file CHANGELOG.md to Unix format...
dos2unix: converting file cleanup.py to Unix format...
dos2unix: converting file config.py to Unix format...
dos2unix: converting file LICENSE.txt to Unix format...
dos2unix: converting file README.md to Unix format...
root@i7:~/new/namesilo-letsencrypt-0.9.2# cksum *
2874061085 3215 authenticator.py
2915655169 1050 CHANGELOG.md
3936447672 3029 cleanup.py
1879213304 147 config.py
4010482586 1509 LICENSE.txt
1108605589 1725 README.md
root@i7:~/new/namesilo-letsencrypt-0.9.2# 
</pre>

**Comment by ethauvin** [comment]
@vinayakrk Good catch, I have no idea why that would be the case, the archive was made on Ubuntu.

I'll investigate, and fix it.

Thanks.

**Comment by vinayakrk** [comment]
Appreciate the quick response.
