### ISSUE TITLE
Thank you message

### ISSUE THREAD

**Issue by Zeioth** [ethauvin/namesilo-letsencrypt#4]
Hey thank you so much for making this. Using your repo I've been able to create an scheduled job on GitLab and now I don't need to care about SSL ever again.

**Comment by ethauvin** [comment]
@Zeioth Awesome. I'm running a cronjob on my server too. It's pretty reliable, but don't be surprised if once in a while it fails. NameSilo sometimes doesn't update the DNS records within the allotted time. It usually fixes itself the next time around.

**Comment by Zeioth** [comment]
Got it thank you so much!! I will run the script every 30 days then just to be sure!

I had to change this block in the cleanup.py

    if xml.namesilo.reply.code.cdata != '280':
            sys.exit(1)

by just 

``` python
if xml.namesilo.reply.code.cdata == '280':
    # Silence 280 errors
    sys.exit(0)
else:
    sys.exit(1)
```
Because I noticed that consistently, namesilo is able to remove the "_acme-challenge" dns record correctly, but still returns [280 code](https://www.namesilo.com/api-reference). So it's not an actuall error, but it's reported as such.

I do this to avoid that GitLab counts the job as error by mistake, because I wanna keep an eye on it in case there is an actual error.

**Comment by ethauvin** [comment]
@Zeioth Interesting. I wonder if that's what I was experimenting too, I just assumed NameSilo had issues.

Let me know how it works out for you after a while. I might just make your change permanent.
