### ISSUE TITLE
COPR package

### ISSUE THREAD

**Issue by cyqsimon** [ethauvin/namesilo-letsencrypt#7]
Thanks for the good work. Kinda saved my arse when I found out Namesilo does not support NS records on a subdomain, which precludes spinning up a local dnsmasq instance for the challenge which is what I normally do.

Anyways, personally I do not like installing software unmanaged, so I packaged this thing on Fedora COPR for Fedora and RHEL [over here](https://copr.fedorainfracloud.org/coprs/cyqsimon/namesilo-letsencrypt/). Makes life a bit easier for me and other people on these OSes.

This issue is just to let you know; feel free to put this info in README (or not, it's your project 😁).

**Comment by ethauvin** [comment]
@cyqsimon That is very cool. Thanks.

Would you mind submitting a PR with the info added to the README?
